server:
  error:
    include-stacktrace: never
  port: 9001

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ponto_venda_spring?createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update